### ISSUE TITLE
Zoom-in/Zoom-out scrolls the page issue

### ISSUE THREAD

**Issue by sushantgwr87** [darkroomengineering/lenis#13]
Hello, I have been using this amazing and simple package for smooth scrolling on various projects. Thanks to all authors and contributors.

Now, problem is that normal zoom-in and zoom-out does not work. Like page does zooms in but it also scrolls the page up and down respectively.

For reference, you can check your own demo as well.

**Comment by clementroche** [comment]
Hi, thank you for your feeback. Actually zoom-in/zoom-out works, the text you see in the demo is not affected because its size is `vw` based. However scroll should be stopped while zooming.
Issue fixed by [this commit](https://github.com/studio-freight/lenis/commit/094dbf5b11d3e1b9359486fc38b1b60a88352c51).
