### ISSUE TITLE
Incorrect scroll limit when using custom wrapper element

### ISSUE THREAD

**Issue by ashthornton** [darkroomengineering/lenis#143]
**Describe the bug**
When using a custom wrapper element, the scroll limit doesn't include the full available scroll area if the element has a bottom margin.

**To Reproduce**
See this codepen: https://codepen.io/ashthornton/pen/oNPyeRP
The scroll bar doesn't reach the bottom

Suggestion: could you use `wrapper.scrollHeight` in your limit calculation?

**Comment by clementroche** [comment]
To be honest I wasn't aware of this property, thank you.

One big benefit of Lenis is that you don't need to trigger update or whatever to recompute sizes when content changes, it's made automatically thanks to resizeObserver. Indeed, using `wrapper.scrollHeight` gonna fix this issue but to keep the seamless resize this requires to causes reflow on every content resize. In the same time, by getting the limit with `wrapper.scrollHeight - wrapper.offsetHeight` we could totally remove content from the codebase (which is awesome). So I guess it's a decision to take.

Maybe we could keep resizeObserver but add a debounce to prevent reflow every frame so we keep content size computation felxibility, fix this issue and remove content from Lenis codebase.

**Comment by ashthornton** [comment]
My feeling is that since the browser does a bunch of reflow on resize anyway, plus the fact that sites will most likely have JS components that require recalcing on resize too, an extra recalc in the mix isn't going to have a huge impact.

The debounce option sounds good to me, we usually debounce our global resize event in our projects for the same reason.

**Comment by clementroche** [comment]
Update: i've tried to implement what i've described above by removing wrapper and content and use `elementscrollHeight - element.clientHeight` as limit. As i was afraid, there is no  clean way to listen to `element.scrollHeight` changes without add `.update()` method. So i'd prefer to keep automatic limit computation rather than force user to call `.update()` manually (i already imagine the amount of issues), that would be a step backward for me. 

Anyway fix gonna come in the next few days.

**Comment by clementroche** [comment]
fixed in [v1.0.5](https://github.com/studio-freight/lenis/releases/tag/1.0.5), can you confirm @ashthornton

**Comment by ashthornton** [comment]
This slipped by! This works now thanks for implementing!
