### ISSUE TITLE
Smooth nested scroll

### ISSUE THREAD

**Issue by Ricard-Garcia** [darkroomengineering/lenis#259]
**Describe the bug**
Smooth scroll lost when scroll is nested.

**To Reproduce**
I'm using `ReactLenis` component with `root` in a project and using `stop()` to lock the scroll when opening a modal. The problem is that, sometimes modals have scroll overflow and using [these data attributes](https://github.com/studio-freight/lenis#nested-scroll) makes the content scrollable again but without the smooth scroll.

Do I need to `stop()` the root `ReactLenis` component and use a different instance inside the modal or is `Lenis` not supporting nested scrolls with smooth behaviour?

Thanks,
Ricard.

**Comment by clementroche** [comment]
You need to call new Lenis() on every element you need to be smooth scrolled

**Comment by Ricard-Garcia** [comment]
Is there a documentation for this? Could it be possible to instantiate Lenis using `<ReactLenis>` instead of a new instance using `new Lenis()`.

Thanks beforehand, @clementroche.

**Comment by clementroche** [comment]
just use <ReactLenis/> where you need it to be smoothed, just remove the "root" option

**Comment by arzafran** [comment]
@Ricard-Garcia, please if the issue is ReactLenis related, use the [issues board](https://github.com/studio-freight/react-lenis/issues) there, since it could be useful for other users too!

after a quick check I've found someone else already asked that question, and got an answer and examples, [here's the link to that issue](https://github.com/studio-freight/react-lenis/issues/26)

**Comment by Ricard-Garcia** [comment]
That's true, thanks for pointing out the previous issue under the same topic @arzafran !
