### ISSUE TITLE
Scroll wheel not working

### ISSUE THREAD

**Issue by ccrch** [darkroomengineering/lenis#337]
I've already reported this once before but the setup where Lenis was used was quite complicated & hard to debug.

Was trying to figure it out again recently, with some simple esbuild setup - same issue.
So I've set up this super simple, basic example here - http://ccrch.com/lenis-test.html
Loading the script from cdn, then just initialiazing it inline. Minimal css. Still doesn't work.
Script loads, console log registers events, but actual mouse wheel doesn't do anything.
Any idea what could be an issue?

![lenis-test](https://github.com/darkroomengineering/lenis/assets/3459315/074c3696-6361-4ca9-8648-b5d67049a70d)

Weirdly enough - when I copy/paste whole markup into ie. codepen - it works.

I was using Lenis on bunch of sites, ie. https://www.netgiro.is/, https://www.preventncd.eu/, https://npi-umbraco.azurewebsites.net/ with pretty much exactly same esbuild setup, and it just works with no problems whatsoever.

**Comment by clementroche** [comment]
That's is weird indeed, [this codepen](https://codepen.io/ClementRoche/pen/vYQZvMm) works. It seems that your default scroll is `body` instead of `documentElement` by checking `document.scrollingElement`. The [scrollingElement documentation](https://developer.mozilla.org/en-US/docs/Web/API/Document/scrollingElement) says that body is the default scroller when your page is in "quirks mode".  I think you're missing the `<!doctype html>`

Anyway i can fix it on lenis codebase by scrolling the scrollingElement instead of the rootElement but i don't see any reason to remove the `<!doctype html>`. https://heitorhherzog.medium.com/what-happens-when-you-remove-doctype-from-the-html-page-b062e6a0beec

**Comment by ccrch** [comment]
Omg. `<!doctype html>` does the trick!
Thank you so much for the quick reply. 😄

**Comment by clementroche** [comment]
@ccrch you're welcome, just learned about this actually. Did you remove it on purpose or did you just forget to add it, or maybe esbuild doesn't add by default ?

**Comment by ccrch** [comment]
I had it in every other setup except for this one. Heh, it's always those small things. 2-3 hrs of figuring it out with 1 short line of code. 😆

**Comment by clementroche** [comment]
Ok, I think it doesn't make sense to adapt lenis to this issue since this is not standard
