### ISSUE TITLE
No support for keystrokes (up, down, spacebar)

### ISSUE THREAD

**Issue by firstchair** [darkroomengineering/lenis#37]
Hi! First of all loved your presentation at awwwwards!

We are trying to implement Lenis for the first time but we are bumping into no support for keyboard...
Is this something on the roadmap? I guess it wouldn't be too hard to implement right? 
Also nice from an accessibility point of view.

**Comment by jakewhiteley** [comment]
Up, down, spacebar, page up, page down work fine on he Lenis demo site on windows (tested chrome, FF, Edge).

Is this on a public site or a local development site of yours? Is there somewhere we can recreate your issue?

**Comment by gyurmey2** [comment]
Hi!
There is indeed a problem with a11y.
When navigating with the keyboard within one page (for example using skip links), it does not shift focus to the link.

Besides, a great library!

**Comment by jakewhiteley** [comment]
@gyurmey2 is this on desktop or mobile?

**Comment by gyurmey2** [comment]
@jakewhiteley I only tested with the keyboard on the desktop.

**Comment by jakewhiteley** [comment]
@gyurmey2 are you using a screenreader or other assistive technology?

Also, do you have a repo where we can see?

I have tested the lenis site using NVDA, but there isn't a skip link on that.

**Comment by gyurmey2** [comment]
@jakewhiteley no, it's about simple local navigation (within one page). Please see below.

[With lenis.js](https://codepen.io/gyurmey2/pen/NWMErqQ) and [without lenis.js](https://codepen.io/gyurmey2/pen/VwxVjgR).

Please note that in the first case, the focus transition is missing on the elements.

**Comment by BleXor** [comment]
@gyurmey2 

It doesn't focus because you call `e.preventDefault()` on that click listener. When you comment/remove it, it will focus as it should. 

Though I found out that sometimes next keyboard navigation to anchors will freeze/keep screen at the same place, not jumping to the links - try "clicking" footer to header link, and before the scroll ends, try tabbing to next links - the screen won't move to those focused anchors. It will jump to those links only when the scroll animation finishes completely.

**Comment by jakewhiteley** [comment]
@gyurmey2 Thanks for the demo.

@BleXor is correct - the `preventDefault` stops the browser from shifting focus to the target. 

The solution if you want to smooth to your anchor target and have focus acting correctly, is to add `tabindex="-1"` to the target element (thus allowing focus on any element, not just ones with focus built in such as buttons), and then call `.focus()` on that element. You can then remove tabindex on `blur` and `focusout` events.

I put a pen together here: https://codepen.io/jakewhiteleydev/pen/oNdQYgL (needs refining, but you get the idea).

Mobiles have this issue built in - using a screenreader with a mobile (both android and iOS last time I tested) and clicking an anchor on a site with no JS on it gives the behaviour you describe - the screen scrolls to the target, but swiping to tell the screen reader to move focus to the next element simply continues from the link you clicked, instead of the visible section.

I personally use the `tabindex` method by default on all sites I do specifcially to fix this issue, and it looks like it will fix your issue as well.

I don't see this as an issue with Lenis, as the default intended behavior is not to smooth to an anchor.

**Comment by gyurmey2** [comment]
@BleXor, @jakewhiteley You're right, I completely missed it. Thanks!

**Comment by clementroche** [comment]
I'm not sure to understand all your issues but should I consider this issue fixed @firstchair ?

However i found a bug by calling scrollTo with a value greater than limit or lower than 0 the easing is wrong. I should add `clamp(0, value, this.limit)` it will be fixed in the next release.

**Comment by clementroche** [comment]
I also noticed that if your `scrollTo` target is far, there is a rough jump at the end caused by the animation reaching its end. I'm still trying to fix it but it's seems a bit more complex.

**Comment by clementroche** [comment]
> I also noticed that if your `scrollTo` target is far, there is a rough jump at the end caused by the animation reaching its end. I'm still trying to fix it but it's seems a bit more complex.

The previous default easing was wrong and was never reaching 1 smoothly so we tweaked it to be seamless. It's fixed in v0.2.13

**Comment by clementroche** [comment]
Last call @firstchair, is your issue fixed ?

**Comment by firstchair** [comment]
Yes, its working indeed. Thanks!
