### ISSUE TITLE
Could we get scroll direction & velocity even if not smooth?

### ISSUE THREAD

**Issue by ffdead** [darkroomengineering/lenis#99]
Usually something like hiding the header on scroll, is done by checking the scroll direction.

But on mobile (smoothTouch=false) this currently doesn't seem to work since those values are not set unless smooth/smoothTouch

Thanks!

**Comment by clementroche** [comment]
You're right ! However velocity  is not relevant on native scroll. So i'm considering bring back direction only and leave velocity to 0

**Comment by clementroche** [comment]
Should be fixed in [v1.0.0-dev.3](https://github.com/studio-freight/lenis/releases/tag/v1.0.0-dev.3)

**Comment by ffdead** [comment]
Greatness! 

Not sure I agree with the velocity, as lenis fires scroll events for native scroll (which is a good thing so we don't need to rebind to the window scroll on mobile), it could also provide the native scroll velocity for consitency. But `direction` is enough for our current needs. Thanks!

**Comment by clementroche** [comment]
Lenis also supports differents ways of scrolling such as keyboard/arrows etc (any native way) but in those cases velocity should be 0 otherwise you would have a 1000px velocity when CMD+F Search. So we need to find a way to descriminate wheel/touch scroll which is not that simple in a native scroll context.
